### ISSUE TITLE
HOW TO ARRANGE ADDRESSES MANUALLY

### ISSUE THREAD

**Issue by mian132** [lordlessio/airdrop#1]
sir how put receivers addresses manually to airdrop tokens. I an trying to put in this way 
[0x58ea6dd8d800ac86b07865c06c2ff5d365f5dec3][0x79AbddB2e7194907FD9d4554097A20c8c3bE7402] But transection is not executing.

**Comment by netpi** [comment]
hello @mian132  
you could copy file [airdrop.flattener.so](https://github.com/lordlessio/airdrop/blob/master/airdrop.flattener.sol) to http://remix.ethereum.org

**Comment by BugBang** [comment]
hi @netpi 
我想通过这个方式 调用我合约里面的一个 onlyOwner 修饰的方法  是否可行

**Comment by netpi** [comment]
@BugBang 前提你要是owner才可以调用的
